/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import dal.Conexion;
import dao.CategoriaDao;
import dao.CuentaDao;
import dao.TransaccionDao;
import dto.Categoria;
import dto.Cuenta;
import dto.Transaccion;
import factory.FactoryDao;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Uway
 */
public class TransaccionGui extends javax.swing.JInternalFrame {

    public TransaccionGui() {
        initComponents();
        mostrarDatos();
        llenarCombocuenta();
        llenarCombocategoria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        txtMonto = new javax.swing.JTextField();
        txtfecha = new javax.swing.JTextField();
        txttipo = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        cmbidcategoria = new javax.swing.JComboBox<>();
        cmbidcuenta = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelcategoria = new javax.swing.JLabel();
        labelcuenta = new javax.swing.JLabel();
        cmbtipo = new javax.swing.JComboBox<>();

        jLabel1.setText("Monto");

        jLabel2.setText("Fecha");

        jLabel3.setText("Tipo");

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla);

        txtfecha.setText(" ");

        txttipo.setText(" ");

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        cmbidcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1" }));
        cmbidcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbidcategoriaActionPerformed(evt);
            }
        });

        cmbidcuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1" }));
        cmbidcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbidcuentaActionPerformed(evt);
            }
        });

        jLabel4.setText("EXIT");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setText("Categoria");

        jLabel6.setText("Cuenta");

        labelcategoria.setText(".");

        labelcuenta.setText(".");

        cmbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gasto", "Ingreso" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnInsertar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(87, 87, 87)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(cmbidcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbidcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(270, 270, 270)))
                        .addContainerGap(78, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addGap(9, 9, 9)
                        .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbidcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelcategoria))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelcuenta)
                            .addComponent(cmbidcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInsertar))))
                .addGap(121, 121, 121))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        System.out.println(cmbidcategoria.getSelectedItem().toString());
        try {
            TransaccionDao objDao = FactoryDao.getFactoryInstance().geTransaccionDao();
            Transaccion obj = new Transaccion();
            obj.setMonto(Integer.parseInt(txtMonto.getText()));
            obj.setFecha(txtfecha.getText());

            obj.setFK_idCategoria(Integer.parseInt(cmbidcategoria.getSelectedItem().toString()));
            obj.setFk_idcuenta(Integer.parseInt(cmbidcuenta.getSelectedItem().toString()));
            obj.setTipo(cmbtipo.getSelectedItem().toString());

            objDao.insert(obj);
        } catch (Exception ex) {
            Logger.getLogger(TransaccionGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        mostrarDatos();
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void cmbidcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbidcategoriaActionPerformed
       try {
        CategoriaDao objDao = FactoryDao.getFactoryInstance().getNewCategoriaDao();
        Categoria obj=new Categoria();
        obj=objDao.get(Integer.parseInt(cmbidcategoria.getSelectedItem().toString()));
        labelcategoria.setText(""+obj.getNombreCategoria());
       
        
    } catch (Exception e) {
        System.out.print(e);
    }
    }//GEN-LAST:event_cmbidcategoriaActionPerformed

    private void cmbidcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbidcuentaActionPerformed
           try {
        CuentaDao objDao = FactoryDao.getFactoryInstance().getNewCuentaDao();
        Cuenta obj=new Cuenta();
        obj=objDao.get(Integer.parseInt(cmbidcategoria.getSelectedItem().toString()));
        labelcategoria.setText(""+obj.getCuentaId());
       
        
    } catch (Exception e) {
        System.out.print(e);
    }
    }//GEN-LAST:event_cmbidcuentaActionPerformed

    public void mostrarDatos() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Fecha");
        modelo.addColumn("tipo");
        modelo.addColumn("Monto");
        Tabla.setModel(modelo);

        String[] datos = new String[4];
        TransaccionDao objDao = FactoryDao.getFactoryInstance().geTransaccionDao();
        List<Transaccion> lista = new ArrayList();
        lista = objDao.getList();
        for (int i = 0; i < lista.size(); i++) {
            datos[0] = String.valueOf(lista.get(i).getIdTransaccion());
            datos[1] = lista.get(i).getFecha();
            datos[2] = lista.get(i).getTipo();
            datos[3] = String.valueOf(lista.get(i).getMonto());
            modelo.addRow(datos);
        }

        Tabla.setModel(modelo);
    }
    
    public void llenarCombocuenta(){
        this.cmbidcuenta.removeAllItems();
    try {
        CuentaDao objDao = FactoryDao.getFactoryInstance().getNewCuentaDao();
        List<Cuenta> lista = new ArrayList();
        lista = objDao.getList();
        for (int i = 0; i <lista.size(); i++) {
            String cuenta=String.valueOf(lista.get(i).getNombreCuenta());
            cmbidcuenta.addItem(cuenta);
            //System.out.println("/////"+cuenta);
        }
        
    } catch (Exception e) {
        System.out.print(e);
    }
        
    }
    public void llenarCombocategoria(){
        this.cmbidcategoria.removeAllItems();
    try {
        CategoriaDao objDao = FactoryDao.getFactoryInstance().getNewCategoriaDao();
        List<Categoria> lista = new ArrayList();
        lista = objDao.getList();
        for (int i = 0; i <lista.size(); i++) {
            String categoria=String.valueOf(lista.get(i).getNombreCategoria());
            cmbidcategoria.addItem(categoria);
            //System.out.println("/////"+cuenta);
        }
        
    } catch (Exception e) {
        System.out.print(e);
    }
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JComboBox<String> cmbidcategoria;
    private javax.swing.JComboBox<String> cmbidcuenta;
    private javax.swing.JComboBox<String> cmbtipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelcategoria;
    private javax.swing.JLabel labelcuenta;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txttipo;
    // End of variables declaration//GEN-END:variables
}
