/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import dao.CategoriaDao;
import dao.CuentaDao;
import dao.TransaccionDao;
import dto.Categoria;
import dto.Cuenta;
import dto.Transaccion;
import factory.FactoryDao;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Uway
 */
public class TransaccionBusqueda extends javax.swing.JInternalFrame {

    /**
     * Creates new form TransaccionBusqueda
     */
    public TransaccionBusqueda() {
        initComponents();
        llenarcombo();
        llenarcombocuenta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        cmbfecha = new javax.swing.JComboBox<>();
        cmbcuenta = new javax.swing.JComboBox<>();
        btnbuscar = new javax.swing.JButton();
        labelcuenta = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        cmbfecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbcuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcuentaActionPerformed(evt);
            }
        });

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        labelcuenta.setText(".");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnbuscar)
                        .addGap(63, 63, 63)
                        .addComponent(labelcuenta))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(cmbcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnbuscar)
                    .addComponent(labelcuenta))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        mostrarDatos(cmbfecha.getSelectedItem().toString(), Integer.parseInt(labelcuenta.getText()));
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void cmbcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcuentaActionPerformed
              try {
        CuentaDao objDao = FactoryDao.getFactoryInstance().getNewCuentaDao();
        Cuenta obj=new Cuenta();
        obj=objDao.obtenernobbreid(cmbcuenta.getSelectedItem().toString());
        labelcuenta.setText(""+obj.getCuentaId());
       
        
    } catch (Exception e) {
        System.out.print(e);
    }
    }//GEN-LAST:event_cmbcuentaActionPerformed

    public void mostrarDatos(String fecha, int id) {
        DefaultTableModel modelo = new DefaultTableModel();
        
        modelo.addColumn("Hora");
        modelo.addColumn("tipo");
        modelo.addColumn("Monto");
        tabla.setModel(modelo);

        String[] datos = new String[4];
        TransaccionDao objDao = FactoryDao.getFactoryInstance().geTransaccionDao();
        List<Transaccion> lista = new ArrayList();
        lista = objDao.getListFecha(fecha,id);
        for (int i = 0; i < lista.size(); i++) {
          
            datos[0] = lista.get(i).getHora();
            datos[1] = lista.get(i).getTipo();
            datos[2] = String.valueOf(lista.get(i).getMonto());
            modelo.addRow(datos);
        }

        tabla.setModel(modelo);
    }

    public void llenarcombo() {
        cmbfecha.removeAllItems();
        try {
            TransaccionDao objDao = FactoryDao.getFactoryInstance().geTransaccionDao();
            List<Transaccion> lista = new ArrayList();
            lista = objDao.getList();
            for (int i = 0; i < lista.size(); i++) {
                String cuenta = String.valueOf(lista.get(i).getFecha());
                cmbfecha.addItem(cuenta);
            }
        } catch (Exception e) {
        }

    }

    public void llenarcombocuenta() {
        cmbcuenta.removeAllItems();
        try {
            CuentaDao objDao = FactoryDao.getFactoryInstance().getNewCuentaDao();
            List<Cuenta> lista = new ArrayList();
            lista = objDao.getList();
            for (int i = 0; i < lista.size(); i++) {
                String cuenta = (lista.get(i).getNombreCuenta());
                cmbcuenta.addItem(cuenta);
            }
        } catch (Exception e) {
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JComboBox<String> cmbcuenta;
    private javax.swing.JComboBox<String> cmbfecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelcuenta;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
